---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app5-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/assemble-dev-org/backstage-sample-quarkus-app5-gitops